#!/bin/zsh
function Usage() {
	echo "Usage: autogit \"message\" "
	echo "Like This：autogit \"first commit\" "
}
if [[ ! $# -eq 1 ]]; then 
    Usage
    exit
fi
git add . && git commit -m "$1" && git push
